### ISSUE TITLE
Still 1.29 on Flathub

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [flathub/io.otsaloma.nfoview#7]
Dear @otsaloma !

Is it intended to get still 1.29 from Flathub? Currently, your site _(https://otsaloma.io/nfoview/)_ shows a button to install 1.99, but at the end, Flathub still offers just 1.29.

Thanks for your time and effort!

**Comment by otsaloma** [comment]
Thanks for noticing. As you can see in this repo, I thought I updated it last week, but it hasn't gone through. Trying a manual build now.

**Comment by otsaloma** [comment]
1.99 now: https://flathub.org/apps/io.otsaloma.nfoview

**Comment by Tamas-Toth-ebola** [comment]
Yes, thanks!

Because I saw your 1.99 .YAML, at morning I tried to remove my Flathub version and build with Flatpak with your 1.99 .YAML. It went successful, so I got 1.99 with a bit extra work.

'Now' I have removed my manual build, and installed from Flathub again, where finally got 1.99.

Thanks for your time and for the 'correction'... but mostly for the app itself!!!
